// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import static frc.robot.Constants.InputConstants.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Drivetrain;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ArcadeDrive extends CommandBase 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final Drivetrain m_drivetrain;
    private final XboxController m_xboxcontroller;

    double m_deadband;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public ArcadeDrive(Drivetrain subsystem, XboxController xboxcontroller) 
    {
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_drivetrain = subsystem;
        addRequirements(m_drivetrain);

        m_xboxcontroller = xboxcontroller;
        
        m_deadband = DEFAULT_DEADBAND;
        SmartDashboard.putNumber("Deadband", m_deadband);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() 
    {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
        double turning;
        double forward;
        
        //Get deadband value set in SmartDashboard
        m_deadband = SmartDashboard.getNumber("Deadband", DEFAULT_DEADBAND);

        //Checks if joystick value is higher or lower than deadband value
        turning = clampInput(m_xboxcontroller.getX(Hand.kLeft));
        forward = clampInput(m_xboxcontroller.getY(Hand.kLeft));

        //pass in trigger for y if forza drive wants to be implemented
        m_drivetrain.arcadeDrive(forward, turning); 
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
        m_drivetrain.stop();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() 
    {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
    
    public double clampInput(double input) 
    {
        double retval = 0.0;
        
        //Check if input is valid, between -1 <= input <= 1
        if((-1 <= input) && (1 >= input))
        {
            if (Math.abs(input) >= m_deadband)
            {
                retval = (Math.abs(input) - m_deadband)/(1 - m_deadband);

                //Check if value is supposed to be negative
                if(input < 0)
                {
                    retval = -1 * retval;
                } 
            }
        }

        return retval;
    }
}
