// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.subsystems.LauncherController;
import frc.robot.subsystems.Targeting;
import frc.robot.commands.LocateTarget;
import frc.robot.commands.Fire;
import frc.robot.subsystems.Drivetrain;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Feeder;
import frc.robot.subsystems.Launcher;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutoFeed extends SequentialCommandGroup 
{

    public AutoFeed(Drivetrain drivetrain, Feeder feeder, Launcher launcher, LauncherController launcherController, Targeting targeting) 
    {
        
        addCommands(
            new LocateTarget(drivetrain, targeting),

            new Fire(feeder, launcher, launcherController) // I don't know if this will work
        );
    }
}
