// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Climb;

/**
 *
 */
public class RetractClimb extends CommandBase 
{
    private final Climb m_climb;
 
    public RetractClimb(Climb subsystem) 
    {
        m_climb = subsystem;
        addRequirements(m_climb);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() 
    {
    	m_climb.climberDown();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() 
    {
        return true;
    }

    @Override
    public boolean runsWhenDisabled() 
    {
        return false;
    }
}
